### DataSource Properties 
spring:
  datasource:    url: jdbc:h2:mem:flight-fare;DB_CLOSE_DELAY=-1
    username: db-ff-username
    password: db-ff-password
    platform: h2

### Hibernate Properties
  jpa:    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:      ddl-auto: update
    properties:      hibernate:
        format_sql: false
        use_sql_comments: false

### H2 Settings
  h2:    console:      enabled: true
      path: /h2-console  
      