### Database Properties
spring:
  datasource:
    url: jdbc:h2:mem:currency-conversion;DB_CLOSE_DELAY=-1
    username: h2-cc-username
    password: {cipher}09ee93a267e4be056b46f89a11a46c9590fa64872ea854ddd1e2e2a49a21454b
    platform: h2

### Hibernate Properties
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false

### H2 Settings
  h2:
    console:
      enabled: true
      path: /h2-console