##### Database Settings
spring:
  datasource:
    url: jdbc:h2:mem:flight-schedule;DB_CLOSE_DELAY=-1
    username: db-fs-user
    password: db-fs-password
    platform: h2

##### H2-Settings
  h2:
    console:
      enabled: true
      path: /h2-console

##### Hibernate Settings
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false

airline:
    airlineDisabled: 'Emirates Airlines'