##### Database Settings
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:flight-schedule;DB_CLOSE_DELAY=-1
    username: db-fs-user
    password: '{cipher}dfb1be68b99469377612beefc324505a304c5efa03ed9b07c002987e5c716658'
    platform: h2

##### H2-Settings
  h2:
    console:
      enabled: true
      path: /h2-console

##### Hibernate Settings
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false

airline:
    airlineDisabled: Emirates Airlines